### ISSUE TITLE
New beta1 panics when previous version didn't

### ISSUE THREAD

**Issue by itamarst** [anweiss/cddl#114]
One of my tests for the validator involves passing in an empty slice (originating in a Python byte string).

In 0.9.0beta0, this gave a validation error.

In beta1, it panics:

```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Io(Error { kind: UnexpectedEof, message: "failed to fill whole buffer" })', /home/itamarst/.cargo/registry/src/github.com-1ecc6299db9ec823/cddl-0.9.0-beta.1/src/validator/mod.rs:169:76
stack backtrace:
   0: rust_begin_unwind
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/panicking.rs:107:14
   2: core::result::unwrap_failed
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/result.rs:1613:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/result.rs:1295:23
   4: cddl::validator::validate_cbor_from_slice
             at /home/itamarst/.cargo/registry/src/github.com-1ecc6299db9ec823/cddl-0.9.0-beta.1/src/validator/mod.rs:169:38
...
```

In general I would suggest never using `unwrap()` or `expect()` in library APIs unless it's utterly impossible to avoid, since panics are very problematic for library users.

**Comment by anweiss** [comment]
Thanks. Oversight on my part. Will fix.

**Comment by itamarst** [comment]
Thank you!
